Add controllers
DIXX159/java-shareit pull request #1
Opened 2023-02-04 07:34 UTC by DIXX159

Реализованы контроллеры User и Item

2023-02-04 19:12 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User updateUser(@RequestBody UserDto userDto, HttpServletRequest request, @PathVariable Long userId) throws ValidationException, ThrowableException {
при добавлении пользователя есть проверка на валидность Email.
при обновлении такой проверки нет
{
	"id": 1,
	"name": "nameItem",
	"email": "wrong_emailmail.com"
}

2023-02-04 19:13 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.debug("Получен {} запрос {} тело запроса: {}", request.getMethod(), request.getRequestURI(), userDto);
При обновлении пользователя всегда срабатывает проверка на дублирование email. Получается просто поменять имя, логин, не меняя при этом email

2023-02-04 19:19 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    searchingItems.add(items.get(i));
В данном алгоритме 5 раз происходит выборка одного и того же элемента из коллекции. Попробуй переписать так, чтобы элемент брался один раз

2023-02-04 19:20 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/model/ItemData.java
> +public abstract class ItemData<K> {
Класс практически не отличается от UserData. Попробуй убрать копи паст

2023-02-04 19:21 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть несколько предложений по улучшению кода

2023-02-05 09:12 UTC, DIXX159 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User updateUser(@RequestBody UserDto userDto, HttpServletRequest request, @PathVariable Long userId) throws ValidationException, ThrowableException {
исправил

2023-02-05 09:13 UTC, DIXX159 commented on src/main/java/ru/practicum/shareit/item/model/ItemData.java
> +public abstract class ItemData<K> {
исправил

2023-02-05 09:14 UTC, DIXX159 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.debug("Получен {} запрос {} тело запроса: {}", request.getMethod(), request.getRequestURI(), userDto);
исправил

2023-02-05 09:18 UTC, DIXX159 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    searchingItems.add(items.get(i));
исправил

2023-02-05 19:07 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-06 15:17 UTC, merged