Add bookings
DIXX159/java-shareit pull request #2
Opened 2023-02-26 16:11 UTC by DIXX159

2023-03-02 17:34 UTC, EvgenyKoptubenko commented
Если добавить пользователя два раза, то приходит 500, но на самом деле должен быть Conflict

{
	"error": "could not execute statement; SQL [n/a]; constraint [\"PUBLIC.UQ_USER_EMAIL_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ U&'email23\\\\044b2\\\\0444\\\\044b322\\\\0446222\\\\044b2@email.com' )\"; SQL statement:\ninsert into users (id, email, name) values (default, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}

2023-03-02 17:37 UTC, EvgenyKoptubenko commented
Если два раза отправить item, то приходит 500-я ошибка
{
	"error": "query did not return a unique result: 3; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 3"
}

2023-03-02 17:38 UTC, EvgenyKoptubenko commented
Не работает такой запрос
curl --request POST \
  --url http://localhost:8080/bookings \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 3' \
  --data '{
	"id":"11",
	"start":"2023-02-23T18:25:43.511Z",
	"end":"2032-04-23T18:25:43.511Z",
	"bookerId":"3",
	"itemId":"2"
	
}'

Похоже он не может преобразовать дату. Было бы здорово. если бы в ответе приходил нужный формат даты.
Это, если есть желание

2023-03-02 17:44 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>              if (item.getAvailable() != null) {
Тут похоже всегда true. Available не null всегда

2023-03-02 17:47 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                Item item = itemRepository.findItemByIdOrderById(i);
Так искать нужный item неверно. Ты по сути вытаскиваешь все записи из базы данных, а потом ищешь среди них нужный. Попробуй вынести это в запрос к базе данных

2023-03-02 17:48 UTC, EvgenyKoptubenko requested changes
Есть несколько замечаний. Поправь, пожалуйста.

2023-03-03 13:59 UTC, DIXX159 commented
> Если добавить пользователя два раза, то приходит 500, но на самом деле должен быть Conflict
> 
> { "error": "could not execute statement; SQL [n/a]; constraint ["PUBLIC.UQ_USER_EMAIL_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ U&'email23\\044b2\\0444\\044b322\\0446222\\[044b2@email.com](mailto:044b2@email.com)' )"; SQL statement:\ninsert into users (id, email, name) values (default, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement" }

Исправил

2023-03-03 14:00 UTC, KDA86 commented
> Если добавить пользователя два раза, то приходит 500, но на самом деле должен быть Conflict
> 
> { "error": "could not execute statement; SQL [n/a]; constraint ["PUBLIC.UQ_USER_EMAIL_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ U&'email23\\044b2\\0444\\044b322\\0446222\\[044b2@email.com](mailto:044b2@email.com)' )"; SQL statement:\ninsert into users (id, email, name) values (default, ?, ?) [23505-214]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement" }

Исправил

2023-03-03 14:00 UTC, DIXX159 commented
> Не работает такой запрос curl --request POST --url http://localhost:8080/bookings --header 'Content-Type: application/json' --header 'X-Sharer-User-Id: 3' --data '{ "id":"11", "start":"2023-02-23T18:25:43.511Z", "end":"2032-04-23T18:25:43.511Z", "bookerId":"3", "itemId":"2"
> 
> }'
> 
> Похоже он не может преобразовать дату. Было бы здорово. если бы в ответе приходил нужный формат даты. Это, если есть желание

Возьму на заметку. в следующем спринте попробую исправить

2023-03-03 14:03 UTC, DIXX159 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>              if (item.getAvailable() != null) {
в постман тестах есть запрос, где нет поля Available, должен давать 400 ошибку. Без этого не проходят проверки на гитхаб.

2023-03-03 16:35 UTC, DIXX159 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                Item item = itemRepository.findItemByIdOrderById(i);
исправил

2023-03-03 21:09 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-03-04 03:21 UTC, merged