add-item-requests
DIXX159/java-shareit pull request #3
Opened 2023-03-18 12:09 UTC by DIXX159

2023-03-18 20:42 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        assertEquals(bookings.get().size(), 1);
Лучше переставить параметры местами, т.к. слева должно быть проверочное значение, а справа актуальное

2023-03-18 20:43 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        booking2.setStatus(BookingStatus.REJECTED);
В тестах очень много копи паста. Попробуй выделить код в какие-то общие методы

2023-03-18 20:44 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        booking2.setEnd(LocalDateTime.now().minusHours(2));
Тесты отличаются только параметрами. Можно их объединить, передавая туда разные переменные
https://www.baeldung.com/parameterized-tests-junit-5
Попробуй параметризованные тесты, если есть желание.

2023-03-18 20:46 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложение по улучшению тестов

2023-03-19 06:01 UTC, DIXX159 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        booking2.setStatus(BookingStatus.REJECTED);
Перенес в @BeforeEach

2023-03-19 07:21 UTC, DIXX159 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        assertEquals(bookings.get().size(), 1);
сделал.

2023-03-19 07:26 UTC, DIXX159 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        booking2.setEnd(LocalDateTime.now().minusHours(2));
мне так удобнее отслеживать, что все варианты протестированы. насколько критично, если так останется?

2023-03-19 19:48 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        booking2.setEnd(LocalDateTime.now().minusHours(2));
Не критично.

2023-03-19 19:48 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-03-20 12:48 UTC, merged